### ISSUE TITLE
python manage.py runtest --report-args-help html执行报错

### ISSUE THREAD

**Issue by xyd113** [Tencent/QTAF#62]
环境：
macOS: 10.14.5
python3.6
IDE:Pycharm

在manage.py同级目录执行命令python manage.py runtest --report-args-help html报如下错误。
Traceback (most recent call last):
  File "manage.py", line 24, in <module>
    ManagementTools().run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/testbase/management.py", line 687, in run
    cmds = self._load_cmds()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/testbase/management.py", line 640, in _load_cmds
    cmds += self._load_cmd_from_module(sys.modules[__name__])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/testbase/management.py", line 663, in _load_cmd_from_module
    cmds.sort(lambda x, y:cmp_func(x.name, y.name))
TypeError: must use keyword argument for key function

**Comment by guyingzhao** [comment]
此问题已经修复过了， 参考 https://github.com/Tencent/QTAF/pull/50
